### ISSUE TITLE
server rendering causes memory leak

### ISSUE THREAD

**Issue by rajeshsegu** [preactjs/preact-router#191]
We are seeing memory shoot while rendering on server since componentWillUnMount() does not get called in server render. 

```
componentWillMount() {
		ROUTERS.push(this);
		this.updating = true;
	}

componentWillUnmount() {
		if (typeof this.unlisten==='function') this.unlisten();
		ROUTERS.splice(ROUTERS.indexOf(this), 1);
	}
```

`ROUTES` is being held in memory for multiple executions of renderToString() and quickly grows as traffic increases.

**Comment by rajeshsegu** [comment]
@developit you thoughts ?

**Comment by developit** [comment]
Ah - definitely need to move the `push()` into `componentDidMount()`. Good catch!

**Comment by developit** [comment]
Finally did the PR (#232, sorry!!)

**Comment by parveen-jabong** [comment]
@developit I think fix is not merged in master.
I am also facing the same issue. 
In 2.6.1 latest version, I still the `push` in `componentWillMount ` rather than `componentDidMount.`
