### ISSUE TITLE
When the `Link` is clicked, there is no reaction to Ctrl and Shift. And history entries are duplicated.

### ISSUE THREAD

**Issue by zakharkang** [preactjs/preact-router#253]
Hello. I've found that multiple clicks on same `Link` cause duplication of records. And also that clicks on `Link` with the holded <kbd>Ctrl</kbd> and <kbd>Shift</kbd> are not processed, as it should be.
I thought this was a mistake and I hope for understanding. I fixed it and hopefully you use it.

`~42 line` in  `preact-router/src/index.js`:
```Javascript
// ...
function route(url, replace=false) {
	if (typeof url!=='string' && url.url) {
		replace = url.replace;
		url = url.url;
	}

	// only push URL into history if we can handle it
	if (url !== getCurrentUrl() && canRoute(url)) {
		setUrl(url, replace ? 'replace' : 'push');
	}

	return routeTo(url);
}
//...
```

`~96 line`:
```Javascript
function handleLinkClick(e) {
	if (e.button==0) {
		if(e.ctrlKey || e.shiftKey) return true;

		prevent(e);

		routeFromLink(e.currentTarget || e.target || this);
	}
}
// ...
```

Thank you in advance.

P.S. Does the `preact-router` cache pages? Let's say when going back and forward on history.

**Comment by developit** [comment]
Hi there - try using a plain old `<a>` element.

**Comment by tysonmatanich** [comment]
@developit Using a plain old `<a>` works correctly but then looses the behavior that `<Link activeClassName="active">` was designed for.
