### ISSUE TITLE
Preact-router does not reinitate components. State being maintained when navigating back to page.

### ISSUE THREAD

**Issue by combojs** [preactjs/preact-router#290]
It appears that a component's state is retained when the router navigates away, and then back to it. I'm initializing the state in the component's constructor function. It appears preact-router does not recreate the components - which means state is never reinitialized.

Is this the expected behavior or a bug? I read somewhere that adding keys to your routes will make preact-router remount the components, but that doesn't take care of my issue either. I also read you should never clear state inside ComponentWillUnmount. Is their a way with preact-router to force a component to be rendered on a route change? If not, I need to look into other solutions, because this will effect all my websites.

Example: https://mvcc.tinytake.com/sf/MjgxMTY5MF84NDM3Mjc5

**Comment by developit** [comment]
This is intended when the components matched for subsequent routes have the same constructor.

Adding keys to your routes should fix the issue:

```js
<Router>
  <A path="/" key="a" />
  <A path="/1" key="1" />
  <A path="/2" key="2" />
</Router>
```

**Comment by MatteoWebDeveloper** [comment]
What about dynamic pages? I suspect it is not going to work

```jsx
<Router>
  <A path="/name/:id" key="1" />
</Router>
```

**Comment by marvinhagemeister** [comment]
To reiterate @developit 's comment: This is the intended behavior. A component should only remount when the `key` changes.
