### ISSUE TITLE
Multiple path names for a same component in Preact Router

### ISSUE THREAD

**Issue by kilgarenone** [preactjs/preact-router#317]
Is it possible to use the same component for multiple different routes?

Like `<ServiceType path=["/cleaning", "/printing", "/accounting"] />`

So that my URL would look like 
`http://mysite.com/cleaning`
`http://mysite.com/printing` 
`http://mysite.com/accounting`

And they are all handled in the same component `<ServiceType  />`.

Is this possible?

**Comment by higimo** [comment]
maybe:

```
<Router>
  <ServiceType path="/cleaning" />
  <ServiceType path="/printing" />
  <ServiceType path="/accounting" />
</Router>
```
