### ISSUE TITLE
Multiple routes rendered at once

### ISSUE THREAD

**Issue by d3x7r0** [preactjs/preact-router#329]
After moving to Preact X and using hooks I started noticing something weird happening with the `useLayoutEffect` hook that I was using to store the scroll position when exiting a route.

After some investigation what I found is that, in some conditions, the router will actually have both the outgoing and the incoming route rendered on screen at the same time.

Here's a reduced test case. Clicking the link will change from the route `Foo` to the route `Bar` and will print the current html of the page as seen by the cleanup function of the `useLayoutEffect` hook:

https://codesandbox.io/embed/admiring-rain-0st62

You can see that during the cleanup function both `Foo` and `Bar` are rendered in the dom at the same time (which makes reading from the DOM on the hook useless for my use case sadly).

**Comment by d3x7r0** [comment]
After going deeper into this I managed to reproduce it without using preact-router at all. Looks like an issue with Preact X itself. I [opened a bug there](https://github.com/preactjs/preact/issues/1886) instead. Sorry.

**Comment by marvinhagemeister** [comment]
Awesome :tada: No need to apologize. Timing issues are always hard to debug. We're super thankful that you reported it so that we have a chance at fixing it :+1:
