### ISSUE TITLE
Link completley reloads the app if it has a onClick property

### ISSUE THREAD

**Issue by lakebeach** [preactjs/preact-router#341]
preact-router 3.0.1 does not allow property onClick if it exists it completely reloads the application when clicked.
[example](https://codesandbox.io/embed/confident-ishizaka-00dkn?fontsize=14) "first route" reloads, "second route" navigates. To illustrate the problem the application switches background color 2 seconds after mount. On the "second route" it does not.

**Comment by developit** [comment]
Duplicate of #340. I'm working on a fix. This is related to Preact X.
