### ISSUE TITLE
Matches return false from Match Tag on SSR (Meaningful 1st Pain)

### ISSUE THREAD

**Issue by louischristopherchen** [preactjs/preact-router#344]
hi, I got some issues about matches function when in server.  I check my server(Meaningful 1st Pain) with turn off my javascript. Mathces return false.
```javascript
 <Match path='/someurl'>
          {({ mathces,url }) => {
          console.log(matches) //false
          console.log(url) //nothing
            return matches &&(<Navbar/>);
          }}
        </Match>
```
i try to solve it with send url from my server.js and i set it into unistore

```javascript
 const initialState = { url:req.url  }
 const store = createStore(initialState);
 let state = store.getState();
 let html = render(
          <Provider store={store}>
            <App url={state.urll} />
          </Provider>
        );
```

so i send props url into my <App/>, and use some condition with <Match/>

```javascript
 <Match>
  {({ url }) => {
    if (url === `/someurl ||this.props.url === `/someurl`) return (<Navbar/> );
   }}
 </Match>
```
I'm not sure this better way to do. can i do it just with matches??

**Comment by marvinhagemeister** [comment]
The server doesn't have any concept of browser history. To ensure a correctly rendered output via SSR you need to pass in the initial URL into the router once. This is done by setting the `url` prop of the surrounding `Router` component. By doing so you don't need to introduce additional conditions for each `Match` component.

```jsx
<Router url="/my/initial/url">
  ...
</Router>
```

**Comment by louischristopherchen** [comment]
Okay thank you @marvinhagemeister . 
My <App> component

```javascript
<div>
<matches>
 {(url)=>
 <navbar url={url||this.props.url}/>
 }
</matches>
<matches>
 {(url)=>
 <router url={url||this.props.url}/>
 }
</matches>
<matches>
 {(url)=>
 <footer url={url||this.props.url}/>
 }
</matches>
</div>
```
why i need this, when i do page reload : url = null, this.props.url=/someurl .
when de different thing is when i click  <a href="/anotherurl/> : url=/anotherurl, this.props.url 
this works, but i diunno this best practice or not.
