### ISSUE TITLE
Type '{ path: string; }' is not assignable to type 'IntrinsicAttributes'.

### ISSUE THREAD

**Issue by evenfrost** [preactjs/preact-router#348]
I'm getting the following error with Preact X, preact-router 3.1.0 and TypeScript 3.7.2:

![Screenshot from 2019-12-03 11-29-17](https://user-images.githubusercontent.com/3055750/70033381-632cb580-15c0-11ea-84b5-efca827568e8.png)

It happens when pages are functional components.

**Comment by marvinhagemeister** [comment]
Yeah, we can't extend the type for `props` for existing component definitions. Setting the `path` property directly on "foreign" components will clash with TypeScript's type checking. For these cases we ship a `Route` component which has the necessary types assigned to it:

```jsx
import { Router, Route } from "preact-router";

<Router>
  <Route path="/foo">
    ...
  </Route>
  ...
</Router>
```

**Comment by alexboots** [comment]
To save anyone else seeing this a few mins, the API for <Route> is

`<Route path="/path" component={ComponentName} />`
