### ISSUE TITLE
React-router v4 example is not working

### ISSUE THREAD

**Issue by montyx99** [preactjs/preact-router#351]
Description:
I cannot implement the example of the usage of the react-router v4. As far as I see the tutorial example is not working too:
https://codepen.io/developit/pen/BWxepY?editors=1010

What I expect:
I'd like to use the react-router v4 with a hashrouter setup in my application. Also I'd like to learn from a working tutorial example, which is based on the preact create default <appname>. The current one is very far from it both in structure, and coding style.

**Comment by marvinhagemeister** [comment]
To use React libraries with Preact you need to enable our compatibility layer. Make sure that you are using a Preact version `>10.x` and follow our documentation on how to alias `react` to `preact/compat` https://preactjs.com/guide/v10/getting-started/#aliasing-react-to-preact

**Comment by montyx99** [comment]
@marvinhagemeister thanks for the feedback. A little question: will be the tutorial linked in the documentation be fixed?

**Comment by marvinhagemeister** [comment]
@montyx99 Works fine for me here. What's the error or unexpected behavior you're getting on your end?

**Comment by lazarljubenovic** [comment]
The docs say that it should work without the compatibility layer:

> React Router 4 even works directly with Preact, no compatibility layer needed!

However, there are no instructions on setting that up. Do I need the `react-router-dom` as well as `react-router`? Where do I import `react-router`? How do I set it up?

OP's Codepen isn't opening for me either. I just see a white page; no errors in the console.
