### ISSUE TITLE
route() does not always trigger the route

### ISSUE THREAD

**Issue by RyanChristian4427** [preactjs/preact-router#357]
I'm trying to build a simple auth guard with the router, just something that will redirect away if the route isn't public and the user is not logged in. This auth guard works just fine when navigating with the `Link` component, but when manually editing the URL, `route()` fails silently.

The following is my router.

```
export const App: preact.FunctionalComponent = () => {
    const [currentUrl, setCurrentUrl] = useState<string>(getCurrentUrl());

    const publicRoutes = ['/register', '/login'];

    const authGuard = (): void => {
        if (!publicRoutes.includes(currentUrl) && jwtService.getToken() == null) {
            console.log('Should be redirection');
            route('/login', true);
        }
    };

    return (
        <div id="app">
            {authGuard()}
            <Router onChange={(e: RouterOnChangeArgs): void => setCurrentUrl(e.url)}>
                <Route path="/" component={Home} />
                <Route path="/login" component={Login} />
                <Route path="/register" component={Register} />
            </Router>
        </div>
    );
};
```

When navigating to `/` manually, as in typing in the address bar, the console log message appears, but the route does not send me to `/login`. It passes me straight through to the `Home` component.

It's of course possible that I'm misunderstanding something here, but as of now, it seems like a bug to me.

Edit: Fixed code formatting

**Comment by developit** [comment]
Hi there - in this case you definitely don't want to be using `route()`, since if that did work it would create an infinite loop. Instead, pass `url` to `Router`.

```js
export const App: preact.FunctionalComponent = () => {
    let [currentUrl, setCurrentUrl] = useState<string>(getCurrentUrl());

    const publicRoutes = ['/register', '/login'];

    if (!publicRoutes.includes(currentUrl) && jwtService.getToken() == null) {
        console.log('Should be redirection');
        url = '/login';
    }

    return (
        <div id="app">
            <Router url={currentUrl} onChange={(e: RouterOnChangeArgs): void => setCurrentUrl(e.url)}>
                <Route path="/" component={Home} />
                <Route path="/login" component={Login} />
                <Route path="/register" component={Register} />
            </Router>
        </div>
    );
};
```

Also just a note - there's no reason to invoke `authGuard()` from within JSX like you were doing, it's functionally identical to just removing the function entirely and running it within render, since it returns undefined and is executed unconditionally.

Personally, I don't think this pattern for handling authenticated routes is the best approach, since it causes excessive re-rendering just to show an unrelated page. I tend to steer folks towards something like this, which doesn't rely on mirroring the `url` as state (causes extra rendering):

```js
export const App = () => {
    const publicRoutes = ['/register', '/login'];
    return (
        <div id="app">
            <Router>
                <AuthenticatedRoute path="/" component={Home} />
                <Route path="/login" component={Login} />
                <Route path="/register" component={Register} />
            </Router>
        </div>
    );
};

function AuthenticatedRoute({ component, ...props }) {
    const isLoggedIn = jwtService.getToken() != null;

    useEffect(() => {
        if (!isLoggedIn) {
            route('/login', true);
        }
    }, [isLoggedIn]);

    // not logged in, render nothing:
    if (!isLoggedIn) return null;

    const Child = component;
    return <Child {...props} />;
}
```

**Comment by RyanChristian4427** [comment]
Sorry, I did eventually find a working solution that looked like this:

```
const App: FunctionalComponent = () => {
    const authStore = useContext(AuthStoreContext);

    const publicRoutes = ['/register', '/login'];

    const authGuard = (e: RouterOnChangeArgs): void => {
        if (!publicRoutes.includes(e.url) && !authStore.isAuthenticated) route('/auth/login');
    };

    return (
        <div id="app">
            <Router onChange={authGuard}>
                <Route path="/" component={Home} />
                <Route path="/login" component={Login} />
                <Route path="/register" component={Register} />
            </Router>
        </div>
    );
};
```

I more or less came to realize the exact things you mention, though I forgot to update the issue.

Thanks for the advice though, I'll probably switch over something close to what you suggest, as it makes sense. I greatly appreciate your help.
