### ISSUE TITLE
Alternative to componentWillMount in Redirect

### ISSUE THREAD

**Issue by donkeyDau** [preactjs/preact-router#361]
The README proposes this code to create a redirect.

```
import { Component } from 'preact';
import { route } from 'preact-router';

export default class Redirect extends Component {
  componentWillMount() {
    route(this.props.to, true);
  }

  render() {
    return null;
  }
}
```

but according to https://preactjs.com/guide/v10/components#lifecycle-methods `componentWillMount` is deprecated. Which lifecycle method is a proper replacement?

**Comment by gtsop** [comment]
Any updates on this please?

**Comment by developit** [comment]
`componentWillMount` is not deprecated in Preact. The `Redirect` implementation posted here seems fine to me.

**Comment by donkeyDau** [comment]
So why is it labeled as (deprecated) in the docs (https://preactjs.com/guide/v10/components#lifecycle-methods)?
