### ISSUE TITLE
Link middle-click

### ISSUE THREAD

**Issue by bturner1273** [preactjs/preact-router#374]
So default behavior for an anchor/link on a middle click is to open a new tab at the link href. However, the server I am using to handle serving the preact page has no concept of the preact-router routes and (obviously) errors out on the new tab.

Is there a way that people usually handle this or is this an issue?

**Comment by Kanaye** [comment]
You 'll need to either: Use somesing like SSR so your server can handle the urls. Or return the entry-html with your preact router for _all_ URLs Serverside. Otherwise things like users reloading the page (or restarting their browser) will also see 404s
