### ISSUE TITLE
Typescript hash router error

### ISSUE THREAD

**Issue by sriksm19** [preactjs/preact-router#385]
tried using the snippet given in the example for [custom history](https://github.com/preactjs/preact-router#custom-history) (i need it for the hash-router). getting the following typescript error

![image](https://user-images.githubusercontent.com/1223117/95468976-adc74d00-099c-11eb-9621-a6bec1f85b43.png)

**Comment by rschristian** [comment]
I assume you're using `history` as the snippet is? If so, the snippet was written before `history` released v5, and I assume that's what you're using. You can downgrade to `history` v4 if you'd like to keep using it. v5's types are incompatible with this library.

**Comment by sriksm19** [comment]
oh. thank you!

**Comment by rschristian** [comment]
It might be worth keeping this open for visibility.

I'll try to whip up a quick PR tomorrow to get some more detail in the ReadMe. Hopefully will help people avoid this pitfall.

**Comment by rzhq** [comment]
I wrote an adapter if you really want to use `history` v5
```js
import { HashHistory } from 'history';
import { CustomHistory } from 'preact-router';

export const hashHistoryAdapter = (hashHistory: HashHistory): CustomHistory => {
  return {
    listen: (callback) => hashHistory.listen(({ location }) => callback(location)),
    location: hashHistory.location,
    push: hashHistory.push,
    replace: hashHistory.replace
  };
};
```

**Comment by rschristian** [comment]
Support for v5 was added in #410
