### ISSUE TITLE
Publish new release?

### ISSUE THREAD

**Issue by oofdog** [preactjs/preact-router#392]
#386 is really helpful and I'd appreciate if you made a patch-level or minor release so we can use it. thanks!

**Comment by liquidboy** [comment]
agree ..  a new release would be much appreciated :) .. 

There is no UMD in the current releases 3.2.1 dists  and seems like the current changes in packages.json fixes this

**Comment by oofdog** [comment]
Any update? @cristianbote @developit

**Comment by cyyynthia** [comment]
A new release would be highly appreciated now that #191 has been fixed, as memory usage can go really high really quickly for apps that receive a fair amount of traffic :/

**Comment by sirianni** [comment]
Any update on this @marvinhagemeister or @developit ?  Would be great to have a new release :pray: !

**Comment by oofdog** [comment]
Looks like they've deployed a new release, so I'm closing.
