### ISSUE TITLE
Allow to set a custom prefix?

### ISSUE THREAD

**Issue by staeff777** [preactjs/preact-router#396]
Sometimes it would be useful to have single page applications that don't require a server configuration and that can run from any possible location. For this use, as far as I know, it would be necessary to use a hash prefix like "page.html#!/site". I used it sucessfully with mithril ( https://mithril.js.org/route.html#routing-strategies ).

In my opinion, this would also make sense in the preact router. Do you agree?

**Comment by rschristian** [comment]
Sorry for the late response, but you can use `history` to create a hash router like you'd want. We outline how in our ReadMe: https://github.com/preactjs/preact-router#custom-history

**Comment by staeff777** [comment]
Thanks. For some reason I didn't find it.
