### ISSUE TITLE
Preact Router adding __source=[object Object] to all dom nodes

### ISSUE THREAD

**Issue by mrispoli24** [preactjs/preact-router#407]
I'm having a small issue where I notice that when I'm using the onChange handler for preact router and passing in some props saved as state to components I seem to get this `__source=[object Object]` appended to all nodes in the app.

Is this normal or some type of development property?

![image](https://user-images.githubusercontent.com/5890462/136088340-2e755f24-d2b2-4e7f-b797-d3b2c4171988.png)

**Comment by jaxreiff** [comment]
I'm getting this as well.

**Comment by miyacoz** [comment]
i don't think that's due to preact-router because i also see them in my preact project though i've not added preact-router yet.

here's my dependencies in package.json:

```json
{
  "devDependencies": {
    "@types/styled-components": "^5.1.15",
    "eslint": "^8.3.0",
    "npm-run-all": "^4.1.5",
    "parcel": "^2.0.1",
    "prettier": "^2.5.0",
    "typescript": "^4.5.2"
  },
  "dependencies": {
    "preact": "^10.6.1",
    "recoil": "^0.5.2",
    "styled-components": "^5.3.3"
  }
}
```

**Comment by developit** [comment]
This happens when you have Babel configured to transpile JSX in development mode, but have not imported `preact/debug`. Something like this works in most bundlers:

```js
if (process.env.NODE_ENV === 'development') {
  require('preact/debug');
}
```
