### ISSUE TITLE
Router and context question

### ISSUE THREAD

**Issue by Schmell** [preactjs/preact-router#430]
I am trying to wrap routes with a context provider and i am getting errors.
Is this possible with preact-router??

```jsx
const MyContext = createContext()
...

<Router>
    <MyContext.Provider>
        <Route path="/somepath" component={SomeComp}/>
    </MyContext.Provider>
...

**Comment by rschristian** [comment]
Could you be a bit more specific than "getting errors"?

That should work just fine.

**Comment by Schmell** [comment]
```
TypeError: Cannot read properties of undefined (reading 'replace')
    at segmentize (util.js?4228:69:1)
    at rank (util.js?4228:77:1)
    at rankChild (util.js?4228:81:1)
    at prepareVNodeForRanking (util.js?4228:64:1)
    at Array.filter (<anonymous>)
    at Router.getMatchingChildren (index.js?a178:208:1)
    at Router.render (index.js?a178:227:1)
```

**Comment by rschristian** [comment]
Ah, my bad.

Children of `<Router>` need to be routes. Context will need to wrap the router.

**Comment by Schmell** [comment]
Ya i knew that worked, but in my case it will put all variables on the an almost global scope. 
I think i can do it with nested routes, I just have to get used to the idea of having routes all over the place

**Comment by rschristian** [comment]
That's usually the point of context, to put values on a global scope. If you just want to provide a context for a single route, why not put the `<MyContext.Provider>` within the route component itself, rather than wrapping the route?

Nested routes, AFAIK, are not supported.

**Comment by Schmell** [comment]
Ya i hear what you are saying, but i want to share some values between routes and _ideally_ only these routes.
Here is a better example of what i am trying to do.
```jsx
const MyContext = createContext()
...
const [myContext, setContext] = useState({})
<Router>
    <Route path="/" component={Home}/>
    ...other routes
    <MyContext.Provider value={{myContext, setMyContext}}>
        <Route path="/somepath" component={SomeComp}/>
        <Route path="/otherpath" component={OtherComp}/>
    </MyContext.Provider>
    ... more routes etc...
...
```
Other routers definitely have this ability as i am trying to do this based on a tut is saw.

I am reading the preact-router docs and there is a section on nested routers
https://github.com/preactjs/preact-router#nested-routers
That being said i have not made it work so far. Of course there is probably another way to do this. I just liked this approach when i saw it

Thanks for your help guys!!

**Comment by rschristian** [comment]
> Other routers definitely have this ability

`preact-router` has historically been a very simple router, not supporting features that many others have (you can usually use them in place of `preact-router`)

> I am reading the preact-router docs and there is a section on nested routers

Ah, missed that, you're totally right. I'll correct that comment.

**Comment by Schmell** [comment]
Hey thanks

**Comment by rschristian** [comment]
You could switch over to [`preact-iso`](https://npm.im/preact-iso) which better supports this and, in general, is recommended over router here nowadays.
