### ISSUE TITLE
TypeScript error "Could not find a declaration file for module preact-router"

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [preactjs/preact-router#443]
Do you know how to get rid of this error? 🤔

![image](https://user-images.githubusercontent.com/668160/235335472-654a0b01-b156-4b64-b038-6025aafd9e9a.png)

My source code is here .. https://github.com/cloudy-net/Cloudy.CMS/tree/master/Cloudy.CMS.UI/wwwroot-src

**Comment by jhirvioja** [comment]
Opened a PR for this to get the ball rolling: https://github.com/preactjs/preact-router/pull/444

**Comment by rschristian** [comment]
In the meantime, you can use an older (and more stable) `moduleResolution` value in your `tsconfig.json`.
