### ISSUE TITLE
Could not find a declaration file for module 'preact-router'

### ISSUE THREAD

**Issue by ArtyomGinoyan** [preactjs/preact-router#447]
### this my code below
`import Router from 'preact-router';`
`import Home from './Home';`
`import Guest from './Guest';`

`export const App = () => {`
 `    return (`
              ` <>`
                     `<Router>`
                           `<Home path='/' /> `
                           `<Guest path='guest' />`
                     `</Router>`
              ` </>`
      `)`
`}`

##### There are types at 'c:/Users/user/Desktop/other/preact_1/node_modules/preact-router/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'preact-router' library may need to update its package.json or typings

**Comment by rschristian** [comment]
Probably a duplicate of #443? What `"moduleResolution"` option are you using in your `tsconfig.json`?

**Comment by ArtyomGinoyan** [comment]
thanks, I had to change moduleResolution from bundler to Node in tsconfig.json
