### ISSUE TITLE
preact-router not resolving route with params after refresh

### ISSUE THREAD

**Issue by espinosakev24** [preactjs/preact-router#462]
I'm having this issue when I refresh the page and the route is using parameters:
![image](https://github.com/preactjs/preact-router/assets/51680218/a6d94efa-da32-4bf4-9b44-375a554eb9aa)

When I navigate to TestPage, it works as expected, but after refresh it throws:
**GET http://localhost:5173/test/src/index.jsx net::ERR_ABORTED 404 (Not Found)**

I'm using vite, no special config, just:

![image](https://github.com/preactjs/preact-router/assets/51680218/04f3430a-1e07-4f8a-8f67-c68a76e2e314)

vite@4.4.9
preact-router@4.1.2
preact@10.17.0

**Comment by rschristian** [comment]
I can't reproduce this: https://stackblitz.com/edit/vitejs-vite-deqijd?file=src%2Fmain.jsx
